# Site settings
baseurl = "http://jorgelbg.github.io/"
themesDir = "themes/"
languageCode = "en-us"
title = "Jorge Luis Betancourt"
theme = "jorgelbg"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-115201846-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""
# publishDir="docs"
# For a list of color schemes, see https://xyproto.github.io/splash/docs/all.html
pygmentsstyle = "fruity"
# Enable "```" for code blocks
pygmentscodefences = true
pygmentsUseClasses = true

[params]
	name = "Jorge Luis Betancourt"
	description = "Computo Ergo Sum"
	bio = "Backend Engineer. I play with Search, Relevance and Web Performance."
	# Enter optionally your twitter account
	twitter = "jorgelbg"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/custom.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Software engineer with a passion for data, search and performance"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/jorgelbgm"
    # facebook = "https://www.facebook.com/"
    github   = "https://github.com/jorgelbg"
    # dribble  = "https://www.dribbble.com/"

[permalinks]
  posts = "/:year/:month/:title/"
