version: 2
jobs:
  build:
    # branches:
    #   ignore:
    #     - hugo
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    
    environment:
      - HUGO_BUILD_DIR: ~/hugo/public
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    
    steps:
      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout
      - run: git submodule sync

      # - run:
      #     name: Install and configure dependencies
      #     command: |
      #       npm install -g --silent gh-pages@2.0.1
      #       git config user.email "ci-build@klukas.net"
      #       git config user.name "ci-build"

      # build with Hugo
      - run: HUGO_ENV=production hugo -v

      # - run:
      #     name: test our generated HTML files
      #     command: |
      #       htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
      #       --empty-alt-ignore --disable-external

      # - run:
      #     name: Deploy docs to gh-pages branch
      #     command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html
      - run:
          name: list files
          command: |
            cd ./public && ls -lA

      - run:
          name: commit generated HTMl files
          command: |
            cd ./public && git add -A && git commit -m "CircleCI article from ${CI_PULL_REQUEST}"

      - run:
          name: push generated HTMl files to master
          command: |
            cd ./public && git push
