version: 2
jobs:
  build:
    # branches:
    #   ignore:
    #     - hugo
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    
    environment:
      - HUGO_BUILD_DIR: ~/hugo/public
      - USERNAME: "jorgelbg"
      - USEREMAIL: "betancourt.jorge@gmail.com"
      - SOURCE_BRANCH: hugo
      - TARGET_BRANCH: master
    
    steps:
      - add_ssh_keys:
          fingerprints:
            - "da:c7:f1:7a:92:ab:33:17:28:1d:cb:40:97:fe:e2:8f"

      # install git
      - run: apk update && apk add git python py-pip

      # checkout the repository
      - checkout

      # - run:
      #     name: Install and configure dependencies
      #     command: |
      #       npm install -g --silent gh-pages@2.0.1
      #       git config user.email "ci-build@klukas.net"
      #       git config user.name "ci-build"

      # build with Hugo
      - run: HUGO_ENV=production hugo -v

      # - run:
      #     name: test our generated HTML files
      #     command: |
      #       htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
      #       --empty-alt-ignore --disable-external

      # - run:
      #     name: Deploy docs to gh-pages branch
      #     command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html
      - run:
          name: install dependencies
          command: |
            pip install ghp-import && which ghp-import

      # - run:
      #     name: commit generated HTMl files
      #     command: |
      #       cd ./public && git add -A

      # - run:
      #     name: push generated HTMl files to master
      #     command: |
      #       cd ./public && git push

      - run:
          name: Deploy to github pages
          command: |
            git config --global user.name $USERNAME
            git config --global user.email $USEREMAIL
            ghp-import --no-jekyll -m "New deployment from CircleCI" -b "${TARGET_BRANCH}" --push public
