version: 2
jobs:
  build:
    branches:
      only:
        - hugo
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    
    environment:
      - HUGO_BUILD_DIR: output
      - SOURCE_BRANCH: hugo
      - TARGET_BRANCH: master
    
    steps:
      - add_ssh_keys:
          fingerprints:
            - "da:c7:f1:7a:92:ab:33:17:28:1d:cb:40:97:fe:e2:8f"

      # install git
      - run: apk update && apk add git python py-pip git-fast-import

      # checkout the repository
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote

      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

      - run:
          name: install dependencies
          command: |
            pip install ghp-import && which ghp-import

      - run:
          name: list files to push
          command: | 
            ls -lA output

      - run:
          name: Deploy to github pages
          command: |
            git config --global user.name $USERNAME
            git config --global user.email $USEREMAIL
            ghp-import --no-jekyll -m "New deployment from CircleCI" -b "${TARGET_BRANCH}" --push ${HUGO_BUILD_DIR}
