name: github pages

on:
  push:
    branches:
      - hugo

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 100

      - name: Install git
        run: sudo apt install git

      - name: Fetch tags
        run: git fetch --depth=50 origin +refs/tags/*:refs/tags/*

        # with:
        #   submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: "0.60.1"
          # extended: true

      - name: Install webp
        run: sudo apt install webp

      - name: Convert PNG into WebP
        run: find ./static -name "*.png" -exec sh -c 'cwebp -m 6 -z 9 -q 85 "$1" -o "${1%.png}.webp"' sh {} \;

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
